language: python

env:
  global:
    # Note: TWINE_PASSWORD is set in Travis settings
    - TWINE_USERNAME=stevenjeanette
    # skip py27 (EOL) and linux-32bit (Test get_h->test_nu0 hangs)
    - CIBW_SKIP="cp27-* *-manylinux_i686"
    # update setuptools to latest version
    - CIBW_BEFORE_BUILD="pip install -U setuptools"
    # testing with cibuildwheel
    - CIBW_TEST_REQUIRES=pytest
    - CIBW_TEST_COMMAND="python -m pytest -v {project}/tests"

install:
  - python -m pip install cibuildwheel==1.1.0

script:
  - python -m cibuildwheel --output-dir tmp_dist

stages:
  - lint
  - test
  - coverage
  - name: test_deploy
    if: (NOT type IN (pull_request)) AND (repo = steven-murray/hankel)
  - name: deploy
    if: (NOT type IN (pull_request)) AND (repo = steven-murray/hankel) AND (branch = master) AND (tag IS present)

jobs:
  include:
    - stage: lint
      services: docker
      python: 3.8
      install: python -m pip install pre-commit
      script:
        - pre-commit run -a
      name: Linting on Linux

    - stage: test
      services: docker
      language: python
      python: 3.8
      name: Test on Linux

    - stage: test
      os: osx
      language: generic
      name: Test on MacOS

    - stage: test
      os: windows
      language: shell
      name: Test on Windows
      before_install:
        - |
          if [[ "$TRAVIS_OS_NAME" = windows ]]; then
              choco install python --version 3.8.0
              export PATH="/c/Python38:/c/Python38/Scripts:$PATH"
          fi

    - stage: coverage
      services: docker
      python: 3.8
      install: python -m pip install .[dev] coveralls
      script:
        - python -m pytest --cov hankel --cov-report term-missing -v tests/
        - python -m coveralls
      name: Coverage on Linux

    # Test Deploy source distribution
    - stage: test_deploy
      python: 3.8
      name: Test Deploy
      install: python -m pip install -U setuptools wheel twine
      script: python setup.py sdist --formats=gztar bdist_wheel
      after_success:
       - python -m twine upload --verbose --skip-existing --repository-url https://test.pypi.org/legacy/ dist/*

    # Deploy source distribution
    - stage: deploy
      python: 3.8
      name: Deploy source distribution
      install: python -m pip install -U setuptools wheel twine
      script: python setup.py sdist --formats=gztar bdist_wheel
      after_success: python -m twine upload --skip-existing dist/*
